In [95]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.utils import image_dataset_from_directory

In [96]:
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model
from keras.layers import Input,Conv2D,MaxPooling2D,Dense,UpSampling2D,BatchNormalization,Flatten,Dropout

In [97]:
base_dir = ".\Desktop\dataset\Data"

In [98]:
import os, shutil

In [99]:
train_dir = os.path.join(base_dir,"train")
test_dir = os.path.join(base_dir,"test")
valid_dir = os.path.join(base_dir,"valid")
train_acc = os.path.join(train_dir,"adenocarcinoma")
train_lcc = os.path.join(train_dir,"large.cell.carcinoma")
train_scc = os.path.join(train_dir,"squamous.cell.carcinoma")
train_normal = os.path.join(train_dir,"normal")
test_acc = os.path.join(test_dir,"adenocarcinoma_left.lower")
test_lcc = os.path.join(test_dir,"large.cell.carcinoma")
test_scc = os.path.join(test_dir,"squamous.cell.carcinoma")
test_normal = os.path.join(test_dir,"normal")
valid_acc = os.path.join(valid_dir,"adenocarcinoma_left.lower")
valid_lcc = os.path.join(valid_dir,"large.cell.carcinoma")
valid_scc = os.path.join(valid_dir,"squamous.cell.carcinoma")
valid_normal = os.path.join(valid_dir,"normal")

In [100]:
import pathlib 
train_acc = pathlib.Path(train_acc)
train_lcc = pathlib.Path(train_lcc)
train_scc = pathlib.Path(train_scc)
train_normal = pathlib.Path(train_normal)

In [101]:
train_images_dict = {
    "adenocarcinoma":list(train_acc.glob('*.png')),
    "large_cell_carcinoma":list(train_lcc.glob('*.png')),
    "squamous_cell_carcinoma":list(train_scc.glob('*.png')),
    "normal":list(train_normal.glob('*.png'))
}

In [102]:
train_images_dict['adenocarcinoma']

[WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000000 (6).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000005 (3).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000005 (9).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000008 (10).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000009 (3).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000009 (7).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000013 (4).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000013 (8).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000014 (7).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000015 (10).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000015 (4).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000015 (9).png'),
 WindowsPath('Desktop/dataset/Data/train/adenocarcinoma/000016 (9).png'),
 WindowsPath('Desktop/dataset/Data/t

In [103]:
train_labels_dict = {
    'adenocarcinoma':0,
    'large_cell_carcinoma':1,
    'squamous_cell_carcinoma':2,
    'normal':3
}

In [104]:
import cv2
img = cv2.imread(str(train_images_dict['adenocarcinoma'][0]))
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [106]:
img.shape

(264, 409, 3)

In [107]:
cv2.resize(img,(180,180)).shape

(180, 180, 3)

In [108]:
X,y = [],[]

for names,images in train_images_dict.items():
    for image in images:
        img = cv2.imread(str(image))
        resize_img = cv2.resize(img,(180,180))
        X.append(resize_img)
        y.append(train_labels_dict[names])

In [109]:
X_train = np.array(X)
y_train = np.array(y)

In [110]:
X_train[0]

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [2, 2, 2],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [111]:
test_acc = pathlib.Path(test_acc)
test_lcc = pathlib.Path(test_lcc)
test_scc = pathlib.Path(test_scc)
test_normal = pathlib.Path(test_normal)

In [114]:
test_images_dict = {
    "adenocarcinoma":list(test_acc.glob('*.png')),
    "large_cell_carcinoma":list(test_lcc.glob('*.png')),
    "squamous_cell_carcinoma":list(test_scc.glob('*.png')),
    "normal":list(test_normal.glob('*.png'))
}

In [115]:
X_test,y_test = [],[]

for names,images in test_images_dict.items():
    for image in images:
        img = cv2.imread(str(image))
        resize_img = cv2.resize(img,(180,180))
        X_test.append(resize_img)
        y_test.append(train_labels_dict[names])

In [131]:
X_test = np.array(X_test)
Y_test = np.array(y_test)

In [117]:
valid_acc = pathlib.Path(valid_acc)
valid_lcc = pathlib.Path(valid_lcc)
valid_scc = pathlib.Path(valid_scc)
valid_normal = pathlib.Path(valid_normal)

In [118]:
valid_images_dict = {
    "adenocarcinoma":list(valid_acc.glob('*.png')),
    "large_cell_carcinoma":list(valid_lcc.glob('*.png')),
    "squamous_cell_carcinoma":list(valid_scc.glob('*.png')),
    "normal":list(valid_normal.glob('*.png'))
}

In [119]:
X_valid,y_valid = [],[]

for names,images in valid_images_dict.items():
    for image in images:
        img = cv2.imread(str(image))
        resize_img = cv2.resize(img,(180,180))
        X_valid.append(resize_img)
        y_valid.append(train_labels_dict[names])

In [120]:
X_valid = np.array(X_valid)
Y_valid = np.array(y_valid)

ValueError: cannot reshape array of size 58417200 into shape (601,180,180)

In [121]:
from keras.layers import Input

In [79]:
inputs=Input(shape=(X_train.shape[0], 180, 180, 3))
x = Sequential()(inputs)
x = Conv2D(16,3,padding="same",activation="relu")(x)
x = MaxPooling2D()(x)
x = Conv2D(16,3,padding="same",activation="relu")(x)
x = MaxPooling2D()(x)
x = Conv2D(32,3,padding="same",activation="relu")(x)
x = MaxPooling2D()(x)
x = Conv2D(64,3,padding="same",activation="relu")(x)
x = MaxPooling2D()(x)
x = Flatten()(x)
x = Dense(128,activation="relu")
x = Dense(5,activation="softmax")
model.summary()

ValueError: Input 0 of layer "max_pooling2d_27" is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: (None, 601, 180, 180, 16)

In [6]:
train_dataset = image_dataset_from_directory(
                train_dir,
                image_size=(180,180),
                batch_size=32)
validation_dataset = image_dataset_from_directory(
                valid_dir,
                image_size = (180,180),
                batch_size=32)
test_dataset = image_dataset_from_directory(
                test_dir,
                image_size=(180,180),
                batch_size = 32)

Found 613 files belonging to 4 classes.
Found 72 files belonging to 4 classes.
Found 315 files belonging to 4 classes.


In [7]:
train_dataset

<_BatchDataset element_spec=(TensorSpec(shape=(None, 180, 180, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [122]:
inputs = keras.Input(shape=(180,180,3))
x = keras.layers.Conv2D(filters = 32, kernel_size = 3, activation = "relu")(inputs)
x = keras.layers.MaxPooling2D(pool_size =2)(x)
x = keras.layers.Conv2D(filters = 32, kernel_size=3,activation="relu")(x)
x = keras.layers.MaxPooling2D(pool_size = 2)(x)
x = keras.layers.Flatten()(x)
outputs = keras.layers.Dense(4,activation="softmax")(x)
model = keras.Model(inputs = inputs, outputs = outputs)

In [123]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 180, 180, 3)]     0         
                                                                 
 conv2d_31 (Conv2D)          (None, 178, 178, 32)      896       
                                                                 
 max_pooling2d_30 (MaxPooli  (None, 89, 89, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_32 (Conv2D)          (None, 87, 87, 32)        9248      
                                                                 
 max_pooling2d_31 (MaxPooli  (None, 43, 43, 32)        0         
 ng2D)                                                           
                                                                 
 flatten_7 (Flatten)         (None, 59168)             0   

In [124]:
model.compile(optimizer="rmsprop",
            loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])

In [126]:
history = model.fit(
    X_train,
    y_train,
    epochs=30)

Epoch 1/30
19/19 [==============================] - 11s 560ms/step - loss: 0.0230 - accuracy: 0.9967
Epoch 2/30
19/19 [==============================] - 11s 577ms/step - loss: 0.0312 - accuracy: 0.9967
Epoch 3/30
19/19 [==============================] - 11s 597ms/step - loss: 0.0223 - accuracy: 0.9950
Epoch 4/30
19/19 [==============================] - 11s 573ms/step - loss: 0.9669 - accuracy: 0.9651
Epoch 5/30
19/19 [==============================] - 11s 601ms/step - loss: 0.2617 - accuracy: 0.9684
Epoch 6/30
19/19 [==============================] - 11s 571ms/step - loss: 0.0542 - accuracy: 0.9967
Epoch 7/30
19/19 [==============================] - 11s 563ms/step - loss: 0.0032 - accuracy: 0.9983
Epoch 8/30
19/19 [==============================] - 12s 614ms/step - loss: 0.0273 - accuracy: 0.9967
Epoch 9/30
19/19 [==============================] - 13s 655ms/step - loss: 0.0350 - accuracy: 0.9983
Epoch 10/30
19/19 [==============================] - 15s 817ms/step - loss: 0.0257 - accura

In [134]:
y_test = np.array(y_test)

In [135]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [136]:
model.evaluate(X_test,y_test)

7/7 [==============================] - 1s 89ms/step - loss: 7.4357 - accuracy: 0.4974


[7.435739517211914, 0.49743589758872986]

In [137]:
predictions = model.predict(X_test)
predictions

7/7 [==============================] - 1s 76ms/step


array([[9.99902368e-01, 9.76591473e-05, 5.50185097e-09, 2.62338606e-11],
       [6.77674370e-06, 9.99993205e-01, 1.98703143e-09, 5.58483677e-08],
       [4.05375272e-01, 5.94624400e-01, 3.50971249e-07, 1.48697203e-18],
       [3.85954678e-01, 6.14045322e-01, 7.66290087e-10, 1.02690598e-14],
       [7.23774672e-01, 2.76225239e-01, 1.28945388e-07, 7.24920846e-10],
       [9.99832153e-01, 7.84074886e-14, 1.67760678e-04, 4.56779254e-14],
       [9.99998569e-01, 3.96400992e-07, 1.02863623e-06, 2.06522660e-10],
       [9.99120772e-01, 8.55086895e-04, 2.41453563e-05, 1.52481264e-10],
       [1.30211754e-06, 7.31889145e-08, 6.19191851e-05, 9.99936700e-01],
       [5.38815919e-04, 8.71110037e-02, 9.12350237e-01, 2.14879167e-13],
       [3.90666082e-06, 4.81021374e-01, 1.21339347e-08, 5.18974721e-01],
       [2.83121655e-04, 9.99710143e-01, 6.67627592e-06, 1.97012788e-08],
       [9.96921957e-01, 7.25532766e-04, 3.55848897e-06, 2.34894338e-03],
       [6.44117415e-01, 1.24195992e-07, 3.55882376e

In [150]:
np.argmax(predictions[1])

1

In [151]:
y_test[1]

1